config/routes.rb
Cliente::Application.routes.draw do
  resources :cadastros

end

app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  # GET /cadastros
  # GET /cadastros.xml
  def index
    @cadastros = Cadastro.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cadastros }
    end
  end

  # GET /cadastros/1
  # GET /cadastros/1.xml
  def show
    @cadastro = Cadastro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cadastro }
    end
  end

  # GET /cadastros/new
  # GET /cadastros/new.xml
  def new
    @cadastro = Cadastro.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cadastro }
    end
  end

  # GET /cadastros/1/edit
  def edit
    @cadastro = Cadastro.find(params[:id])
  end

  # POST /cadastros
  # POST /cadastros.xml
  def create
    @cadastro = Cadastro.new(params[:cadastro])

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to(@cadastro, :notice => 'Cadastro was successfully created.') }
        format.xml  { render :xml => @cadastro, :status => :created, :location => @cadastro }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cadastro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cadastros/1
  # PUT /cadastros/1.xml
  def update
    @cadastro = Cadastro.find(params[:id])

    respond_to do |format|
      if @cadastro.update_attributes(params[:cadastro])
        format.html { redirect_to(@cadastro, :notice => 'Cadastro was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cadastro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.xml
  def destroy
    @cadastro = Cadastro.find(params[:id])
    @cadastro.destroy

    respond_to do |format|
      format.html { redirect_to(cadastros_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/views/cadastros/_form.html.erb
<%= form_for(@cadastro) do |f| %>
  <% if @cadastro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>

      <ul>
      <% @cadastro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.text_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editing cadastro</h1>

<%= render 'form' %>

<%= link_to 'Show', @cadastro %> |
<%= link_to 'Back', cadastros_path %>

app/views/cadastros/index.html.erb
<h1>Listing cadastros</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Telefone</th>
    <th>Idade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cadastros.each do |cadastro| %>
  <tr>
    <td><%= cadastro.nome %></td>
    <td><%= cadastro.telefone %></td>
    <td><%= cadastro.idade %></td>
    <td><%= link_to 'Show', cadastro %></td>
    <td><%= link_to 'Edit', edit_cadastro_path(cadastro) %></td>
    <td><%= link_to 'Destroy', cadastro, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cadastro', new_cadastro_path %>

app/views/cadastros/new.html.erb
<h1>New cadastro</h1>

<%= render 'form' %>

<%= link_to 'Back', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cadastro.nome %>
</p>

<p>
  <b>Telefone:</b>
  <%= @cadastro.telefone %>
</p>

<p>
  <b>Idade:</b>
  <%= @cadastro.idade %>
</p>


<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cliente</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>